# Generated by Django 3.0.6 on 2020-06-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('route_short_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_long_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_id', models.CharField(max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('location_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('headsign', models.CharField(blank=True, max_length=50, null=True)),
                ('direction_code', models.IntegerField()),
                ('route', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('destination_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tam.Stop')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tam.Line')),
            ],
            options={
                'unique_together': {('line', 'direction_code')},
            },
        ),
        migrations.AddField(
            model_name='line',
            name='transport_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tam.TransportMode'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tam.Route')),
            ],
        ),
        migrations.CreateModel(
            name='PassingTime',
            fields=[
                ('time_departure', models.DateTimeField()),
                ('time_delay', models.DurationField(default=0, null=True)),
                ('passingtime', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tam.Course')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tam.Stop')),
            ],
            options={
                'unique_together': {('stop', 'course')},
            },
        ),
    ]
